###
POST http://localhost:8000/projects
Authorization: Bearer good
Content-Type: application/json

{
    "name": "Project-1",
    "description": "Description of project 1"
}
> {% client.global.set("project_id", response.body.id); %}
<> 2024-11-03T134659.201.json
<> 2024-11-03T134638.401.json

###
POST http://localhost:8000/projects/{{project_id}}/trials
Content-Type: application/json

{
    "name": "Trial-1"
}

> {% client.global.set("trial_id", response.body.id); %}

###
GET http://localhost:8000/projects/{{project_id}}/trials

###
POST http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/parse
Content-Type: application/json

{
  "config": {
            "modules": [
                {"module_type": "langchain_parse", "parse_method": ["pdfminer"]}
            ]
        },
  "name": "test2"
}

> {% client.global.set("parse_task_id", response.body.id); %}
<> 2024-11-03T134938.202.json

###

GET http://localhost:8000/projects/{{project_id}}/tasks/{{parse_task_id}}


###
POST http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/chunk
Content-Type: application/json

{
  "config": {
            "modules": [
                {"module_type": "llama_index_chunk", "chunk_method": ["Token"]}
            ]
        },
  "name": "test2"
}

> {% client.global.set("chunk_task_id", response.body.id); %}

###
GET http://localhost:8000/projects/{{project_id}}/tasks/{{chunk_task_id}}

###
POST http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/qa
Content-Type: application/json

{
  "preset": "simple",
  "name": "test3",
  "qa_num": 5,
  "llm_config": {
    "llm_name": "mock"
  },
  "lang": "ko"
}

> {% client.global.set("qa_task_id", response.body.id); %}

###
GET http://localhost:8000/projects/{{project_id}}/tasks/{{qa_task_id}}

###
POST http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/config
Content-Type: application/json

{
  "config": {
    "node_lines": [
      {
        "node_line_name": "retrieve_node_line",
        "nodes": [
          {
            "node_type": "retrieval",
            "strategy": {
              "metrics": [
                "retrieval_f1",
                "retrieval_recall",
                "retrieval_precision"
              ]
            },
            "top_k": 3,
            "modules": [
              {
                "module_type": "vectordb",
                "vectordb": "default"
              }
            ]
          }
        ]
      },
      {
        "node_line_name": "post_retrieve_node_line",
        "nodes": [
          {
            "node_type": "prompt_maker",
            "strategy": {
              "metrics": [
                "bleu",
                "meteor",
                "rouge"
              ]
            },
            "modules": [
              {
                "module_type": "fstring",
                "prompt": "Read the passages and answer the given question. \n Question: {query} \n Passage: {retrieved_contents} \n Answer : "
              }
            ]
          },
          {
            "node_type": "generator",
            "strategy": {
              "metrics": [
                "bleu",
                "rouge"
              ]
            },
            "modules": [
              {
                "module_type": "llama_index_llm",
                "llm": "openai",
                "model": [
                  "gpt-4o-mini"
                ]
              }
            ]
          }
        ]
      }
    ]
  }
}

###
GET http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/config

###
POST http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/validate
Content-Type: application/json

{}

> {% client.global.set("validate_id", response.body.id); %}

###
GET http://localhost:8000/projects/{{project_id}}/tasks/{{validate_id}}

###
POST http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/evaluate
Content-Type: application/json

{
  "full_ingest": true,
  "skip_validation": true
}

> {% client.global.set("evaluate_id", response.body.id); %}
###
GET http://localhost:8000/projects/{{project_id}}/tasks/{{evaluate_id}}

###
GET http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/report/open

###
GET http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/report/close

###
GET http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/chat/open

###
GET http://localhost:8000/projects/{{project_id}}/trials/{{trial_id}}/chat/close
