node_lines:
- node_line_name: retrieve_node_line
  nodes:
  - node_type: retrieval
    modules:
    - module_type: vectordb
      embedding_model: openai
    - module_type: bm25
      bm25_tokenizer: [ ko_kiwi, ko_okt, ko_kkma ]
    top_k: 20
    strategy:
      metrics: [ retrieval_recall, retrieval_precision, retrieval_map ]
  - node_type: passage_reranker
    modules:
    - module_type: koreranker
    - module_type: pass_reranker
    - module_type: cohere_reranker
    strategy:
      metrics: [ retrieval_recall, retrieval_precision, retrieval_map ]
    top_k: 3
- node_line_name: post_retrieve_node_line
  nodes:
  - modules:
    - module_type: fstring
      prompt: "주어진 passage만을 이용하여 question에 따라 답하시오 passage: {retrieved_contents} \n\n Question: {query} \n\n Answer:"
    node_type: prompt_maker
    strategy:
      generator_modules:
      - batch: 2
        module_type: openai_llm
      metrics:
        - metric_name: rouge
        - embedding_model: openai
          metric_name: sem_score
        - metric_name: bert_score
          lang: ko
  - modules:
    - batch: 2
      llm: gpt-4o
      module_type: openai_llm
    node_type: generator
    strategy:
      metrics:
      - metric_name: rouge
      - embedding_model: openai
        metric_name: sem_score
      - metric_name: bert_score
        lang: ko
